export const videos = [
  {
    id: "1",
    title: "React JS Full Course 2024 | Learn React from Scratch",
    channelName: "Code With Harry",
    views: "1.2M views",
    uploadedAt: "2 days ago",
    duration: "2:35:20",
    thumbnail: "https://i.ytimg.com/vi/bMknfKXIFA8/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: "2",
    title: "Build YouTube Clone Using React & Tailwind CSS",
    channelName: "JavaScript Mastery",
    views: "850K views",
    uploadedAt: "1 week ago",
    duration: "1:45:10",
    thumbnail: "https://i.ytimg.com/vi/FHTbsZEJspU/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: "3",
    title: "Node.js & Express Crash Course",
    channelName: "Traversy Media",
    views: "2.3M views",
    uploadedAt: "3 months ago",
    duration: "1:30:45",
    thumbnail: "https://i.ytimg.com/vi/fBNz5xF-Kx4/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: "4",
    title: "MongoDB Tutorial for Beginners",
    channelName: "freeCodeCamp.org",
    views: "980K views",
    uploadedAt: "5 days ago",
    duration: "4:12:00",
    thumbnail: "https://i.ytimg.com/vi/ofme2o29ngU/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: "5",
    title: "JavaScript Interview Questions & Answers",
    channelName: "Akshay Saini",
    views: "670K views",
    uploadedAt: "2 weeks ago",
    duration: "55:40",
    thumbnail: "https://i.ytimg.com/vi/8aGhZQkoFbQ/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: "6",
    title: "Tailwind CSS in 1 Hour",
    channelName: "Net Ninja",
    views: "420K views",
    uploadedAt: "6 days ago",
    duration: "1:02:15",
    thumbnail: "https://i.ytimg.com/vi/dFgzHOX84xQ/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=6",
  },
{
  id: "7",
  title: "Complete JavaScript Roadmap 2024",
  channelName: "Code With Harry",
  views: "1.8M views",
  uploadedAt: "1 week ago",
  duration: "1:20:45",
  thumbnail: "https://picsum.photos/seed/yt7/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=7",
},
{
  id: "8",
  title: "React Router v6 Full Tutorial",
  channelName: "JavaScript Mastery",
  views: "920K views",
  uploadedAt: "3 days ago",
  duration: "58:30",
  thumbnail: "https://picsum.photos/seed/yt8/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=8",
},
{
  id: "9",
  title: "Node.js Authentication with JWT",
  channelName: "Traversy Media",
  views: "1.1M views",
  uploadedAt: "2 weeks ago",
  duration: "1:10:22",
  thumbnail: "https://picsum.photos/seed/yt9/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=9",
},
{
  id: "10",
  title: "MongoDB Atlas Complete Guide",
  channelName: "freeCodeCamp.org",
  views: "780K views",
  uploadedAt: "4 days ago",
  duration: "2:05:10",
  thumbnail: "https://picsum.photos/seed/yt10/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=10",
},
{
  id: "11",
  title: "JavaScript Closures Explained",
  channelName: "Akshay Saini",
  views: "640K views",
  uploadedAt: "6 days ago",
  duration: "42:18",
  thumbnail: "https://picsum.photos/seed/yt11/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=11",
},
{
  id: "12",
  title: "Tailwind CSS Crash Course",
  channelName: "Net Ninja",
  views: "560K views",
  uploadedAt: "5 days ago",
  duration: "1:00:40",
  thumbnail: "https://picsum.photos/seed/yt12/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=12",
},
{
  id: "13",
  title: "Build REST API with Express & MongoDB",
  channelName: "Traversy Media",
  views: "1.4M views",
  uploadedAt: "1 month ago",
  duration: "1:35:00",
  thumbnail: "https://picsum.photos/seed/yt13/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=13",
},
{
  id: "14",
  title: "React useEffect Hook Deep Dive",
  channelName: "Code With Harry",
  views: "510K views",
  uploadedAt: "2 weeks ago",
  duration: "39:55",
  thumbnail: "https://picsum.photos/seed/yt14/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=14",
},
{
  id: "15",
  title: "Frontend Interview Preparation",
  channelName: "Akshay Saini",
  views: "870K views",
  uploadedAt: "3 weeks ago",
  duration: "1:25:12",
  thumbnail: "https://picsum.photos/seed/yt15/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=15",
},
{
  id: "16",
  title: "Build YouTube Clone UI in React",
  channelName: "JavaScript Mastery",
  views: "690K views",
  uploadedAt: "4 days ago",
  duration: "1:15:50",
  thumbnail: "https://picsum.photos/seed/yt16/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=16",
},
{
  id: "17",
  title: "Redux Toolkit Explained Simply",
  channelName: "Net Ninja",
  views: "430K views",
  uploadedAt: "1 week ago",
  duration: "48:30",
  thumbnail: "https://picsum.photos/seed/yt17/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=17",
},
{
  id: "18",
  title: "Backend Roadmap for 2024",
  channelName: "freeCodeCamp.org",
  views: "1.9M views",
  uploadedAt: "2 months ago",
  duration: "3:10:00",
  thumbnail: "https://picsum.photos/seed/yt18/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=18",
},
{
  id: "19",
  title: "JWT Authentication Explained",
  channelName: "Traversy Media",
  views: "980K views",
  uploadedAt: "9 days ago",
  duration: "55:45",
  thumbnail: "https://picsum.photos/seed/yt19/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=19",
},
{
  id: "20",
  title: "Advanced JavaScript Concepts",
  channelName: "Akshay Saini",
  views: "1.3M views",
  uploadedAt: "1 month ago",
  duration: "1:40:20",
  thumbnail: "https://picsum.photos/seed/yt20/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=20",
},


 
  
];
