export const videos = [
  {
    id: "1",
    title: "React JS Full Course 2024 | Learn React from Scratch",
    channelName: "Code With Harry",
    subscribers: "1.2M",
    views: "1.2M views",
    uploadedAt: "2 days ago",
    duration: "2:35:20",
    thumbnail: "https://i.ytimg.com/vi/bMknfKXIFA8/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=1",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Learn React from scratch with real projects.",
    likes: 6900,
    comments: [
      {
        id: 1,
        user: "MohitDecodes",
        avatar: "https://i.pravatar.cc/40?img=11",
        text: "This course is 🔥🔥",
        likes: 33,
        time: "4 months ago",
      },
      {
        id: 2,
        user: "funadda7359",
        avatar: "https://i.pravatar.cc/40?img=12",
        text: "Great explanation for beginners",
        likes: 8,
        time: "3 months ago",
      },
    ],
  },

  {
    id: "2",
    title: "Build YouTube Clone Using React & Tailwind CSS",
    channelName: "JavaScript Mastery",
    subscribers: "980K",
    views: "850K views",
    uploadedAt: "1 week ago",
    duration: "1:45:10",
    thumbnail: "https://i.ytimg.com/vi/FHTbsZEJspU/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=2",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    description: "Build a YouTube clone UI using React & Tailwind.",
    likes: 4200,
    comments: [
      {
        id: 1,
        user: "JyotiYadav",
        avatar: "https://i.pravatar.cc/40?img=13",
        text: "UI looks exactly like YouTube 😍",
        likes: 23,
        time: "4 months ago",
      },
    ],
  },

  {
    id: "3",
    title: "Node.js & Express Crash Course",
    channelName: "Traversy Media",
    subscribers: "2.4M",
    views: "2.3M views",
    uploadedAt: "3 months ago",
    duration: "1:30:45",
    thumbnail: "https://i.ytimg.com/vi/fBNz5xF-Kx4/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=3",
    videoUrl: "https://www.youtube.com/embed/fBNz5xF-Kx4",
    description: "Complete Node.js & Express crash course.",
    likes: 8200,
    comments: [
      {
        id: 1,
        user: "DevJourney",
        avatar: "https://i.pravatar.cc/40?img=14",
        text: "Traversy never disappoints 🙌",
        likes: 41,
        time: "2 months ago",
      },
      {
        id: 2,
        user: "backendGeek",
        avatar: "https://i.pravatar.cc/40?img=15",
        text: "Best Node.js explanation so far",
        likes: 19,
        time: "1 month ago",
      },
    ],
  },

  {
    id: "4",
    title: "MongoDB Tutorial for Beginners",
    channelName: "freeCodeCamp.org",
    subscribers: "7.5M",
    views: "980K views",
    uploadedAt: "5 days ago",
    duration: "4:12:00",
    thumbnail: "https://i.ytimg.com/vi/ofme2o29ngU/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=4",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    description: "Learn MongoDB from scratch with hands-on examples.",
    likes: 5600,
    comments: [
      {
        id: 1,
        user: "dbMaster",
        avatar: "https://i.pravatar.cc/40?img=16",
        text: "This cleared all my MongoDB doubts 🔥",
        likes: 27,
        time: "2 weeks ago",
      },
    ],
  },

  {
    id: "5",
    title: "JavaScript Interview Questions & Answers",
    channelName: "Akshay Saini",
    subscribers: "1.1M",
    views: "670K views",
    uploadedAt: "2 weeks ago",
    duration: "55:40",
    thumbnail: "https://i.ytimg.com/vi/8aGhZQkoFbQ/maxresdefault.jpg",
    channelAvatar: "https://i.pravatar.cc/150?img=5",
    videoUrl: "https://www.youtube.com/embed/8aGhZQkoFbQ",
    description: "Most asked JavaScript interview questions explained.",
    likes: 9100,
    comments: [
      {
        id: 1,
        user: "frontendPro",
        avatar: "https://i.pravatar.cc/40?img=17",
        text: "Got confidence after watching this 💯",
        likes: 38,
        time: "1 week ago",
      },
      {
        id: 2,
        user: "jobSeeker",
        avatar: "https://i.pravatar.cc/40?img=18",
        text: "Helped me crack my interview!",
        likes: 21,
        time: "5 days ago",
      },
    ],
  },
  {
  id: "6",
  title: "Tailwind CSS in 1 Hour",
  channelName: "Net Ninja",
  subscribers: "1.3M",
  views: "420K views",
  uploadedAt: "6 days ago",
  duration: "1:02:15",
  thumbnail: "https://i.ytimg.com/vi/dFgzHOX84xQ/maxresdefault.jpg",
  channelAvatar: "https://i.pravatar.cc/150?img=6",
  videoUrl: "https://www.youtube.com/embed/dFgzHOX84xQ",
  description: "Learn Tailwind CSS from scratch in just one hour.",
  likes: 3100,
  comments: [
    {
      id: 1,
      user: "cssLover",
      avatar: "https://i.pravatar.cc/40?img=19",
      text: "Tailwind finally makes sense 🔥",
      likes: 15,
      time: "5 days ago",
    },
    {
      id: 2,
      user: "uiBuilder",
      avatar: "https://i.pravatar.cc/40?img=20",
      text: "Clean and simple explanation 👌",
      likes: 9,
      time: "4 days ago",
    },
  ],
},

{
  id: "7",
  title: "Complete JavaScript Roadmap 2024",
  channelName: "Code With Harry",
  subscribers: "1.2M",
  views: "1.8M views",
  uploadedAt: "1 week ago",
  duration: "1:20:45",
  thumbnail: "https://picsum.photos/seed/yt7/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=7",
  videoUrl: "https://www.youtube.com/embed/PkZNo7MFNFg",
  description: "Complete JavaScript roadmap from beginner to advanced.",
  likes: 7600,
  comments: [
    {
      id: 1,
      user: "jsBeginner",
      avatar: "https://i.pravatar.cc/40?img=21",
      text: "This roadmap is GOLD 🏆",
      likes: 42,
      time: "6 days ago",
    },
  ],
},

{
  id: "8",
  title: "React Router v6 Full Tutorial",
  channelName: "JavaScript Mastery",
  subscribers: "980K",
  views: "920K views",
  uploadedAt: "3 days ago",
  duration: "58:30",
  thumbnail: "https://picsum.photos/seed/yt8/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=8",
  videoUrl: "https://www.youtube.com/embed/59IXY5IDrBA",
  description: "Master React Router v6 with real examples.",
  likes: 4800,
  comments: [
    {
      id: 1,
      user: "reactFan",
      avatar: "https://i.pravatar.cc/40?img=22",
      text: "Finally understood nested routes 🙌",
      likes: 18,
      time: "2 days ago",
    },
  ],
},

{
  id: "9",
  title: "Node.js Authentication with JWT",
  channelName: "Traversy Media",
  subscribers: "2.4M",
  views: "1.1M views",
  uploadedAt: "2 weeks ago",
  duration: "1:10:22",
  thumbnail: "https://picsum.photos/seed/yt9/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=9",
  videoUrl: "https://www.youtube.com/embed/mbsmsi7l3r4",
  description: "JWT authentication explained step by step.",
  likes: 6700,
  comments: [
    {
      id: 1,
      user: "backendDev",
      avatar: "https://i.pravatar.cc/40?img=23",
      text: "Best JWT explanation on YouTube",
      likes: 29,
      time: "1 week ago",
    },
  ],
},

{
  id: "10",
  title: "MongoDB Atlas Complete Guide",
  channelName: "freeCodeCamp.org",
  subscribers: "7.5M",
  views: "780K views",
  uploadedAt: "4 days ago",
  duration: "2:05:10",
  thumbnail: "https://picsum.photos/seed/yt10/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=10",
  videoUrl: "https://www.youtube.com/embed/-56x56UppqQ",
  description: "Complete MongoDB Atlas tutorial for beginners.",
  likes: 3900,
  comments: [
    {
      id: 1,
      user: "dbLearner",
      avatar: "https://i.pravatar.cc/40?img=24",
      text: "Atlas setup was confusing before this 😅",
      likes: 11,
      time: "3 days ago",
    },
  ],
},

{
  id: "11",
  title: "JavaScript Closures Explained",
  channelName: "Akshay Saini",
  subscribers: "1.1M",
  views: "640K views",
  uploadedAt: "6 days ago",
  duration: "42:18",
  thumbnail: "https://picsum.photos/seed/yt11/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=11",
  videoUrl: "https://www.youtube.com/embed/qikxEIxsXco",
  description: "Closures explained in the simplest way possible.",
  likes: 5200,
  comments: [
    {
      id: 1,
      user: "jsConfused",
      avatar: "https://i.pravatar.cc/40?img=25",
      text: "Now closures finally clicked 💡",
      likes: 24,
      time: "4 days ago",
    },
  ],
},

{
  id: "12",
  title: "Tailwind CSS Crash Course",
  channelName: "Net Ninja",
  subscribers: "1.3M",
  views: "560K views",
  uploadedAt: "5 days ago",
  duration: "1:00:40",
  thumbnail: "https://picsum.photos/seed/yt12/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=12",
  videoUrl: "https://www.youtube.com/embed/UBOj6rqRUME",
  description: "Crash course on Tailwind CSS with real examples.",
  likes: 3500,
  comments: [
    {
      id: 1,
      user: "designGeek",
      avatar: "https://i.pravatar.cc/40?img=26",
      text: "Tailwind saves so much time 😍",
      likes: 17,
      time: "3 days ago",
    },
  ],
},
{
  id: "13",
  title: "Build REST API with Express & MongoDB",
  channelName: "Traversy Media",
  subscribers: "2.4M",
  views: "1.4M views",
  uploadedAt: "1 month ago",
  duration: "1:35:00",
  thumbnail: "https://picsum.photos/seed/yt13/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=13",
  videoUrl: "https://www.youtube.com/embed/l8WPWK9mS5M",
  description: "Build a complete REST API using Express and MongoDB.",
  likes: 8800,
  comments: [
    {
      id: 1,
      user: "apiBuilder",
      avatar: "https://i.pravatar.cc/40?img=27",
      text: "This is exactly what I needed 🙏",
      likes: 34,
      time: "3 weeks ago",
    },
  ],
},

{
  id: "14",
  title: "React useEffect Hook Deep Dive",
  channelName: "Code With Harry",
  subscribers: "1.2M",
  views: "510K views",
  uploadedAt: "2 weeks ago",
  duration: "39:55",
  thumbnail: "https://picsum.photos/seed/yt14/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=14",
  videoUrl: "https://www.youtube.com/embed/Tn6-PIqc4UM",
  description: "Deep dive into React useEffect hook with examples.",
  likes: 4600,
  comments: [
    {
      id: 1,
      user: "reactLearner",
      avatar: "https://i.pravatar.cc/40?img=28",
      text: "Best explanation of useEffect so far!",
      likes: 21,
      time: "10 days ago",
    },
  ],
},

{
  id: "15",
  title: "Frontend Interview Preparation",
  channelName: "Akshay Saini",
  subscribers: "1.1M",
  views: "870K views",
  uploadedAt: "3 weeks ago",
  duration: "1:25:12",
  thumbnail: "https://picsum.photos/seed/yt15/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=15",
  videoUrl: "https://www.youtube.com/embed/8zKuNo4ay8E",
  description: "Prepare for frontend interviews with real questions.",
  likes: 9200,
  comments: [
    {
      id: 1,
      user: "jobReady",
      avatar: "https://i.pravatar.cc/40?img=29",
      text: "Helped me crack my frontend interview 💯",
      likes: 47,
      time: "2 weeks ago",
    },
  ],
},

{
  id: "16",
  title: "Build YouTube Clone UI in React",
  channelName: "JavaScript Mastery",
  subscribers: "980K",
  views: "690K views",
  uploadedAt: "4 days ago",
  duration: "1:15:50",
  thumbnail: "https://picsum.photos/seed/yt16/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=16",
  videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  description: "Build a YouTube clone UI using React and Tailwind CSS.",
  likes: 5400,
  comments: [
    {
      id: 1,
      user: "cloneBuilder",
      avatar: "https://i.pravatar.cc/40?img=30",
      text: "Following this for my final project 🚀",
      likes: 18,
      time: "3 days ago",
    },
  ],
},

{
  id: "17",
  title: "Redux Toolkit Explained Simply",
  channelName: "Net Ninja",
  subscribers: "1.3M",
  views: "430K views",
  uploadedAt: "1 week ago",
  duration: "48:30",
  thumbnail: "https://picsum.photos/seed/yt17/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=17",
  videoUrl: "https://www.youtube.com/embed/iBUJVy8phqw",
  description: "Redux Toolkit explained in a simple and practical way.",
  likes: 3900,
  comments: [
    {
      id: 1,
      user: "stateManager",
      avatar: "https://i.pravatar.cc/40?img=31",
      text: "Redux finally feels easy 😄",
      likes: 14,
      time: "6 days ago",
    },
  ],
},

{
  id: "18",
  title: "Backend Roadmap for 2024",
  channelName: "freeCodeCamp.org",
  subscribers: "7.5M",
  views: "1.9M views",
  uploadedAt: "2 months ago",
  duration: "3:10:00",
  thumbnail: "https://picsum.photos/seed/yt18/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=18",
  videoUrl: "https://www.youtube.com/embed/XBu54nfzxAQ",
  description: "Complete backend developer roadmap for 2024.",
  likes: 10200,
  comments: [
    {
      id: 1,
      user: "backendDream",
      avatar: "https://i.pravatar.cc/40?img=32",
      text: "This roadmap is insanely helpful 🔥",
      likes: 56,
      time: "1 month ago",
    },
  ],
},

{
  id: "19",
  title: "JWT Authentication Explained",
  channelName: "Traversy Media",
  subscribers: "2.4M",
  views: "980K views",
  uploadedAt: "9 days ago",
  duration: "55:45",
  thumbnail: "https://picsum.photos/seed/yt19/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=19",
  videoUrl: "https://www.youtube.com/embed/mbsmsi7l3r4",
  description: "JWT authentication explained clearly and practically.",
  likes: 6100,
  comments: [
    {
      id: 1,
      user: "authLearner",
      avatar: "https://i.pravatar.cc/40?img=33",
      text: "Security concepts made simple 👍",
      likes: 22,
      time: "1 week ago",
    },
  ],
},

{
  id: "20",
  title: "Advanced JavaScript Concepts",
  channelName: "Akshay Saini",
  subscribers: "1.1M",
  views: "1.3M views",
  uploadedAt: "1 month ago",
  duration: "1:40:20",
  thumbnail: "https://picsum.photos/seed/yt20/400/225",
  channelAvatar: "https://i.pravatar.cc/150?img=20",
  videoUrl: "https://www.youtube.com/embed/R9I85RhI7Cg",
  description: "Deep dive into advanced JavaScript concepts.",
  likes: 11800,
  comments: [
    {
      id: 1,
      user: "jsMaster",
      avatar: "https://i.pravatar.cc/40?img=34",
      text: "Akshay’s explanations are next level 🚀",
      likes: 63,
      time: "3 weeks ago",
    },
  ],
},

];
